apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example-appconfig
spec:
  components:
    - name: example-component
      type: webservice
      properties:
        image: nginx:latest
      traits:
        - type: scaler
          properties:
            replicas: 3
